
package Interface;

import bigproject.*;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class EditGroup extends javax.swing.JFrame {
    public String invokingName;
    WordGroup invokingWordGroup;
    
    public EditGroup(String name) {
        initComponents();
        invokingName = name;
        invokingWordGroup = new WordGroup(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topic = new javax.swing.JLabel();
        addWord = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        deleteW = new javax.swing.JButton();
        panelSuaTu = new javax.swing.JPanel();
        word = new javax.swing.JLabel();
        mean = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        tfMeanning = new javax.swing.JTextField();
        lImageSource = new javax.swing.JLabel();
        cbImageSource = new javax.swing.JComboBox<>();
        addImage = new javax.swing.JButton();
        tfLink = new javax.swing.JTextField();
        jScrollPane = new javax.swing.JScrollPane();
        tListWord = new javax.swing.JTable();
        save = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sửa Bộ Từ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        topic.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        topic.setForeground(new java.awt.Color(0, 102, 153));
        topic.setText("TOPIC");

        addWord.setText("Thêm Từ");
        addWord.setToolTipText("Click để thêm từ mới");
        addWord.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWordActionPerformed(evt);
            }
        });

        edit.setText("Sửa Từ");
        edit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        deleteW.setText("Xóa Từ");
        deleteW.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteWActionPerformed(evt);
            }
        });

        panelSuaTu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelSuaTu.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                panelSuaTuComponentHidden(evt);
            }
        });

        word.setText("Từ");

        mean.setText("Nghĩa");

        lImageSource.setText("Nguồn");

        cbImageSource.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trong máy", "URL" }));

        addImage.setText("Hình Ảnh");
        addImage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSuaTuLayout = new javax.swing.GroupLayout(panelSuaTu);
        panelSuaTu.setLayout(panelSuaTuLayout);
        panelSuaTuLayout.setHorizontalGroup(
            panelSuaTuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuaTuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSuaTuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSuaTuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(mean, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                        .addComponent(word, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lImageSource)
                    .addComponent(addImage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSuaTuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMeanning, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbImageSource, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLink, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        panelSuaTuLayout.setVerticalGroup(
            panelSuaTuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuaTuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSuaTuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(word)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(panelSuaTuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mean)
                    .addComponent(tfMeanning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelSuaTuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lImageSource)
                    .addComponent(cbImageSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelSuaTuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addImage)
                    .addComponent(tfLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tListWord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Từ", "Nghĩa", "Link Ảnh", "Lần học cuối", "Thời gian nghỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tListWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tListWordMouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(tListWord);

        save.setText("Lưu");
        save.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setFocusable(false);

        lImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(panelSuaTu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(topic, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(65, 65, 65)
                        .addComponent(lImage, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addWord, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteW, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(topic, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(panelSuaTu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lImage, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addWord, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteW, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteWActionPerformed
        DefaultTableModel model = (DefaultTableModel) tListWord.getModel();
        
        int confirm = JOptionPane.showConfirmDialog(rootPane, "Bạn chắc muốn xóa từ này?");
        
        if(confirm == 0) {
            invokingWordGroup.remove(model.getValueAt(tListWord.getSelectedRow(), 0).toString());
            
            refreshTListWord();
        }
    }//GEN-LAST:event_deleteWActionPerformed

    private void addWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWordActionPerformed
        invokingWordGroup.addWord(tfName.getText(), tfMeanning.getText(), tfLink.getText());
        
        panelSuaTu.setVisible(true);
        refreshTListWord();
    }//GEN-LAST:event_addWordActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        DefaultTableModel model = (DefaultTableModel) tListWord.getModel();
        
        String describedInitialWord = 
                model.getValueAt(tListWord.getSelectedRow(), 0).toString() + "\t" +
                model.getValueAt(tListWord.getSelectedRow(), 1).toString() + "\t" +
                model.getValueAt(tListWord.getSelectedRow(), 2).toString() + "\t" +
                model.getValueAt(tListWord.getSelectedRow(), 3).toString() + "\t" +
                model.getValueAt(tListWord.getSelectedRow(), 4).toString() + "\t\r\n";
        Word initial = new Word(describedInitialWord);
        
        //String[] describedResultWord = 
        Word result = new Word(tfName.getText(),tfMeanning.getText(),tfLink.getText(),
                model.getValueAt(tListWord.getSelectedRow(), 3).toString(),
                model.getValueAt(tListWord.getSelectedRow(), 4).toString());
        
        invokingWordGroup.editWord(initial, result);
        
        panelSuaTu.setVisible(true);
        refreshTListWord();
    }//GEN-LAST:event_editActionPerformed

    private void panelSuaTuComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panelSuaTuComponentHidden
        panelSuaTu.setVisible(false);
    }//GEN-LAST:event_panelSuaTuComponentHidden

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        this.dispose();
    }//GEN-LAST:event_saveActionPerformed

    private void addImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addImageActionPerformed
        JFileChooser brower = new JFileChooser();
        brower.showOpenDialog(null);
        File f = brower.getSelectedFile();
        String filename = f.getAbsolutePath();     
        tfLink.setText(filename);     
    }//GEN-LAST:event_addImageActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jLabel1.setText(invokingName);
        refreshTListWord();
    }//GEN-LAST:event_formWindowOpened

    private void tListWordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tListWordMouseClicked
        DefaultTableModel model = (DefaultTableModel) tListWord.getModel();
        
        //Set text to TextField
        tfName.setText(model.getValueAt(tListWord.getSelectedRow(), 0).toString());
        tfMeanning.setText(model.getValueAt(tListWord.getSelectedRow(), 1).toString());
        tfLink.setText(model.getValueAt(tListWord.getSelectedRow(), 2).toString());
        
        //Display image
        if(cbImageSource.getSelectedItem().toString().equals("Trong máy")){
            
            BufferedImage img = null;
            try {
                img = ImageIO.read(new File(model.getValueAt(tListWord.getSelectedRow(), 2).toString()));
            } catch (IOException e) {
                //e.printStackTrace();
            }
            
            Image dimg = img.getScaledInstance(lImage.getWidth(), lImage.getHeight(),
                    Image.SCALE_SMOOTH);

            
            //lImage.setIcon(new ImageIcon(model.getValueAt(tListWord.getSelectedRow(), 2).toString()));
            lImage.setIcon(new ImageIcon(dimg));
            
        } else if(cbImageSource.getSelectedItem().toString().equals("URL")) {
            
            BufferedImage img = null;
            try {
                img = ImageIO.read(new URL(model.getValueAt(tListWord.getSelectedRow(), 2).toString()));
            } catch (IOException e) {
                //e.printStackTrace();
            }
            
            Image dimg = img.getScaledInstance(lImage.getWidth(), lImage.getHeight(),
                    Image.SCALE_SMOOTH);
            
//            try {
//                lImage.setIcon(new ImageIcon(new URL(model.getValueAt(tListWord.getSelectedRow(), 2).toString())));
//            } catch (MalformedURLException ex) {
//                //Logger.getLogger(EditGroup.class.getName()).log(Level.SEVERE, null, ex);
//            }
            
            lImage.setIcon(new ImageIcon(dimg));
        }
    }//GEN-LAST:event_tListWordMouseClicked

    
    public void refreshTListWord() {
        DefaultTableModel model = (DefaultTableModel) tListWord.getModel();
        
        int initialRow = model.getRowCount();
        for(int i = initialRow - 1 ; i >= 0 ; i--) {
            model.removeRow(i);
        }
        invokingWordGroup.sort();
        String[][] list = invokingWordGroup.getWordListStringArray();
        for(int i=0;i<list.length;i++) {
//            Object[] detail = new Object[2];
//            detail[0] = list[i].name;
//            detail[1] = list[i].getSoTu();
            model.addRow(list[i]);
        }
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addImage;
    private javax.swing.JButton addWord;
    private javax.swing.JComboBox<String> cbImageSource;
    private javax.swing.JButton deleteW;
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lImage;
    private javax.swing.JLabel lImageSource;
    private javax.swing.JLabel mean;
    private javax.swing.JPanel panelSuaTu;
    private javax.swing.JButton save;
    private javax.swing.JTable tListWord;
    private javax.swing.JTextField tfLink;
    private javax.swing.JTextField tfMeanning;
    private javax.swing.JTextField tfName;
    private javax.swing.JLabel topic;
    private javax.swing.JLabel word;
    // End of variables declaration//GEN-END:variables
}
